import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from .integrations.llm_judge import BaseLLM, OpenAIJudge, GigaChatJudge

REPORT_PROMPT_TEMPLATE = """You are a senior RAG systems analyst. Write a clear, structured report \
based on the evaluation metrics below.

[Evaluation Result]
{metrics_json}

[Format]
## Summary
2-3 sentences: overall verdict and business score.

## Retrieval
Comment on data availability, chunking quality, and ranking metrics if present.

## Generation
Comment on faithfulness, SFC, IDS.

## Business
Comment on cost, latency, trust.

## Recommendations
Up to 5 concrete, prioritized action items.
"""


def _summarize(result: Dict[str, Any]) -> Dict[str, Any]:
    """Reduce a full evaluate() result to the fields worth feeding to an LLM (keeps prompts small)."""
    return {
        "final_score": result.get("final_score"),
        "status": result.get("status"),
        "fault_type": result.get("fault_type"),
        "fault_subtype": result.get("fault_subtype"),
        "fault_explanation": result.get("fault_explanation"),
        "core_metrics": {
            k: v for k, v in result.get("metrics", {}).items()
            if isinstance(v, (int, float))
        },
        "data_availability_diagnostic": (result.get("data_availability") or {}).get("diagnostic"),
        "chunking_diagnostics": (result.get("chunking_quality") or {}).get("diagnostics"),
        "business_metrics": result.get("business_metrics", {}),
    }


class LLMReportGenerator:
    """Feeds a RAGEvaluator.evaluate() result to an LLM to produce a human-readable narrative report."""

    def __init__(self, llm: BaseLLM):
        self.llm = llm

    def generate(self, result: Dict[str, Any]) -> str:
        metrics_json = json.dumps(_summarize(result), indent=2, default=str, ensure_ascii=False)
        prompt = REPORT_PROMPT_TEMPLATE.format(metrics_json=metrics_json)
        return self.llm.complete(prompt, temperature=0.2)

    @classmethod
    def create(cls, provider: str, model: str, **kwargs) -> "LLMReportGenerator":
        if provider == "openai":
            llm = OpenAIJudge(model=model, **kwargs)
        elif provider == "gigachat":
            llm = GigaChatJudge(model=model, **kwargs)
        else:
            raise ValueError(f"Unknown provider: {provider}. Use: openai, gigachat")
        return cls(llm=llm)



# Non-LLM structured report — deterministic, works without any API key.
@dataclass
class SectionContent:
    title: str
    content: str
    metrics: Dict[str, Any] = field(default_factory=dict)
    severity: str = "info"  # info, warning, critical


@dataclass
class StructuredReport:
    overall_score: float
    status: str
    fault_type: str
    sections: List[SectionContent]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "overall_score": round(self.overall_score, 2),
            "status": self.status,
            "fault_type": self.fault_type,
            "sections": [
                {"title": s.title, "content": s.content, "metrics": s.metrics, "severity": s.severity}
                for s in self.sections
            ],
        }

    def to_markdown(self) -> str:
        lines = [
            "# RAGNAROK Evaluation Report",
            "",
            f"**Overall Score:** {self.overall_score:.1f}/100",
            f"**Status:** {'PASSED' if self.status == 'PASSED' else self.status}",
            f"**Fault Type:** {self.fault_type.upper()}",
            "",
            "---",
            "",
        ]
        for section in self.sections:
            icon = {"critical": "🔴", "warning": "🟡"}.get(section.severity, "🟢")
            lines += [f"## {icon} {section.title}", "", section.content, ""]
            if section.metrics:
                lines += ["| Metric | Value |", "|--------|-------|"]
                for k, v in section.metrics.items():
                    lines.append(f"| {k} | {v:.3f} |" if isinstance(v, float) else f"| {k} | {v} |")
                lines.append("")
        lines += ["---", "*Generated by RAGNAROK*"]
        return "\n".join(lines)

    def to_html(self) -> str:
        parts = [
            '<div class="ragnarok-report">',
            "<h1>RAGNAROK Evaluation Report</h1>",
            '<div class="summary">',
            f'<span class="score">Score: {self.overall_score:.1f}/100</span> ',
            f'<span class="status {"passed" if self.status == "PASSED" else "failed"}">{self.status}</span> ',
            f'<span class="fault">Fault: {self.fault_type.upper()}</span>',
            "</div>",
        ]
        for section in self.sections:
            parts.append(f'<div class="section {section.severity}">')
            parts.append(f"<h2>{section.title}</h2>")
            parts.append(f"<p>{section.content.replace(chr(10), '<br>')}</p>")
            if section.metrics:
                parts.append("<table><tr><th>Metric</th><th>Value</th></tr>")
                for k, v in section.metrics.items():
                    val = f"{v:.3f}" if isinstance(v, float) else str(v)
                    parts.append(f"<tr><td>{k}</td><td>{val}</td></tr>")
                parts.append("</table>")
            parts.append("</div>")
        parts.append("</div>")
        return "\n".join(parts)


class StructuredReportGenerator:
    """
    Builds a StructuredReport straight from a RAGEvaluator.evaluate() result — no LLM,
    no API key, fully deterministic. Renders to dict/Markdown/HTML. Pair with
    LLMReportGenerator for an optional narrative layer on top of the same data.
    """

    def generate(self, result: Dict[str, Any],
                 retrieval_pipeline_report: Optional[Dict[str, Any]] = None) -> StructuredReport:
        score = result.get("final_score", 0.0)
        status = result.get("status", "UNKNOWN")
        fault = result.get("fault_type", "unknown")

        sections = [
            self._executive_summary(result),
        ]
        if retrieval_pipeline_report:
            sections.append(self._retrieval_pipeline_section(retrieval_pipeline_report))
        sections.append(self._generation_section(result))
        sections.append(self._business_section(result))
        sections.append(self._fault_section(result))
        sections.append(self._recommendations_section(result, retrieval_pipeline_report))
        sections.append(self._action_items_section(result))

        return StructuredReport(overall_score=score, status=status, fault_type=fault, sections=sections)

    @staticmethod
    def _executive_summary(result: Dict[str, Any]) -> SectionContent:
        score = result.get("final_score", 0.0)
        status = result.get("status", "UNKNOWN")
        fault = result.get("fault_type", "unknown")
        explanation = result.get("fault_explanation", "")

        if status == "PASSED":
            text = (f"RAG pipeline performs acceptably with a score of {score:.1f}/100. "
                    f"Classified as '{fault}' with no critical issues detected. {explanation}")
        else:
            text = (f"RAG pipeline shows significant issues — score {score:.1f}/100 (below the 60 threshold). "
                    f"Primary fault: '{fault}'. {explanation} Immediate attention recommended.")

        return SectionContent(
            title="Executive Summary", content=text.strip(),
            metrics={"final_score": score, "status": status, "fault": fault},
            severity="critical" if status == "FAILED" else "info",
        )

    @staticmethod
    def _retrieval_pipeline_section(report: Dict[str, Any]) -> SectionContent:
        lines = ["Retrieval pipeline evaluated across 5 stages:"]
        for stage in report.get("stages", []):
            icon = "PASS" if stage.get("passed") else "FAIL"
            lines.append(f"\n[{icon}] {stage.get('stage_name', 'Unknown')} — {stage.get('summary', '')}")

        bottleneck = report.get("bottleneck_stage")
        if bottleneck:
            lines.append(f"\nBottleneck: {bottleneck} — {report.get('bottleneck_explanation', '')}")

        return SectionContent(
            title="Retrieval Pipeline Diagnostics",
            content="\n".join(lines),
            metrics={"bottleneck": bottleneck or "none"},
            severity="critical" if not report.get("overall_passed", True) else "info",
        )

    @staticmethod
    def _generation_section(result: Dict[str, Any]) -> SectionContent:
        metrics = result.get("metrics", {})
        faith = metrics.get("faithfulness", 0)
        sfc = metrics.get("sfc", 0)
        ids = metrics.get("ids", 0)

        text = (
            f"Faithfulness: {faith:.3f} — "
            f"{'fully grounded' if faith > 0.9 else 'partially grounded' if faith > 0.5 else 'significant hallucination risk'}.\n"
            f"Semantic Footprint Coverage: {sfc:.3f} — "
            f"{'complete coverage' if sfc > 0.8 else 'partial coverage' if sfc > 0.4 else 'major gaps'}.\n"
            f"Information Density: {ids:.4f} — "
            f"{'high density' if ids > 0.5 else 'moderate density' if ids > 0.2 else 'low density / verbose'}."
        )
        return SectionContent(
            title="Generation Quality", content=text,
            metrics={"faithfulness": faith, "sfc": sfc, "ids": ids},
            severity="warning" if faith < 0.7 else "info",
        )

    @staticmethod
    def _business_section(result: Dict[str, Any]) -> SectionContent:
        biz = result.get("business_metrics", {})
        cost_score = biz.get("cost_score", 100)
        latency_grade = biz.get("latency_grade", "N/A")
        trust_score = biz.get("trust_score", 0)

        text = (
            f"Cost efficiency: {cost_score:.1f}/100 — "
            f"{'economical' if cost_score > 80 else 'moderate cost' if cost_score > 50 else 'expensive'}.\n"
            f"Latency grade: {latency_grade}.\n"
            f"Trust score: {trust_score:.3f} — "
            f"{'high trust' if trust_score > 0.85 else 'medium trust' if trust_score > 0.6 else 'low trust'}."
        )
        return SectionContent(
            title="Business Metrics", content=text,
            metrics={"cost_score": cost_score, "latency_grade": latency_grade, "trust_score": trust_score},
            severity="warning" if cost_score < 50 else "info",
        )

    @staticmethod
    def _fault_section(result: Dict[str, Any]) -> SectionContent:
        fault = result.get("fault_type", "unknown")
        subtype = result.get("fault_subtype")
        confidence = result.get("fault_confidence", 0)
        text = f"Detected fault: {fault.upper()}"
        if subtype:
            text += f" (subtype: {subtype})"
        text += f"\nConfidence: {confidence:.0%}\n{result.get('fault_explanation', '')}"
        return SectionContent(
            title="Fault Analysis", content=text,
            metrics={"fault_type": fault, "confidence": confidence},
            severity="critical" if fault != "healthy" else "info",
        )

    @staticmethod
    def _recommendations_section(result: Dict[str, Any],
                                  retrieval_pipeline_report: Optional[Dict[str, Any]]) -> SectionContent:
        recs = []
        action = result.get("recommended_action")
        if action:
            recs.append(f"1. {action}")
        if retrieval_pipeline_report and not retrieval_pipeline_report.get("overall_passed", True):
            recs.append(f"2. {retrieval_pipeline_report.get('bottleneck_explanation', '')}")
        text = "\n\n".join(recs) if recs else "No critical recommendations — system is within acceptable parameters."
        return SectionContent(title="Recommendations", content=text,
                               severity="warning" if result.get("status") == "FAILED" else "info")

    @staticmethod
    def _action_items_section(result: Dict[str, Any]) -> SectionContent:
        actions = []
        score = result.get("final_score", 0)
        fault = result.get("fault_type", "healthy")

        if score < 60:
            actions.append("[CRITICAL] Address the primary fault immediately — score is below the passing threshold.")
        if fault == "generation":
            actions.append("[CRITICAL] Review prompts for citation/grounding requirements.")
        elif fault == "retrieval":
            actions.append("[CRITICAL] Add a cross-encoder reranker to improve ranking.")
        elif fault == "chunking":
            actions.append("[CRITICAL] Redesign chunking strategy (semantic or recursive chunking with overlap).")
        elif fault == "business":
            actions.append("[HIGH] Reduce cost/latency — smaller model, caching, or fewer retrieved chunks.")

        biz = result.get("business_metrics", {})
        if biz.get("latency_grade") in {"POOR", "UNACCEPTABLE"}:
            actions.append("[HIGH] Latency exceeds SLA — optimize retrieval or use a faster model.")

        if not actions:
            actions.append("[LOW] Continue monitoring. No immediate action required.")

        return SectionContent(title="Action Items", content="\n".join(actions),
                               severity="critical" if score < 60 else "info")
